spring.application.name=tracker
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/LeetcodeTracker}
spring.data.mongodb.auto-index-creation=true

# b (You can generate a new one for production later)
application.security.jwt.secret-key=${JWT_SECRET:26f282adb0381c2953321159ed7dd356077ae25e28a59524088eae41ca7df3c9}


# Access Token Expiration (15 minutes = 900000 ms)
application.security.jwt.expiration=${JWT_EXPIR:900000}

# JWT Refresh Token Expiration (7 days = 604800000 ms)
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIR:604800000}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-placeholder-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-placeholder-secret}
spring.security.oauth2.client.registration.google.scope=profile, email